// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sql

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email, key
) VALUES (
  ?, ?, ?
)
RETURNING id, oauth_id, name, email, "key"
`

type CreateUserParams struct {
	Name  string
	Email string
	Key   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Key)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OauthID,
		&i.Name,
		&i.Email,
		&i.Key,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE oauth_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, oauthID string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, oauthID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, oauth_id, name, email, "key" FROM users
WHERE oauth_id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, oauthID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, oauthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OauthID,
		&i.Name,
		&i.Email,
		&i.Key,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, oauth_id, name, email, "key" FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OauthID,
			&i.Name,
			&i.Email,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
set name = ?,
email = ?,
key = ?
WHERE oauth_id = ?
`

type UpdateUserParams struct {
	Name    string
	Email   string
	Key     string
	OauthID string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Key,
		arg.OauthID,
	)
	return err
}
